const datajson = [
    {
      "id": "27771057276452865",
      "functionName": "demo",
      "url": "demo",
      "isFinalnode": 0,
      "icon": "",
      "children": [
        {
          "id": "988829284524716032",
          "functionName": "demo1",
          "url": "/demo",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988829373871779840",
          "functionName": "demo2",
          "url": "/demo",
          "isFinalnode": 1,
          "icon": null,
        },
      ],
    },
    {
      "id": "27771057835132865",
      "functionName": "作业管控",
      "url": "operationControl",
      "isFinalnode": 0,
      "icon": "",
      "children": [
        {
          "id": "988825242112332",
          "functionName": "作业计划",
          "url": "/operationControl$workPlan",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112333",
          "functionName": "区域巡检",
          "url": "/operationControl$areaPatrol",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112334",
          "functionName": "设备巡检",
          "url": "/operationControl$videoPatrol",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112335",
          "functionName": "生产设备",
          "url": "/operationControl$deviceMonitor",
          "isFinalnode": 1,
          "icon": null,
        },
      ],
    },
    {
      "id": "27771057835132868",
      "functionName": "智能巡检",
      "url": "patrols",
      "isFinalnode": 0,
      "icon": "",
      "children": [
        {
          "id": "988825242112332",
          "functionName": "巡视监控",
          "url": "/patrols$taskManage",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112332",
          "functionName": "线路管理",
          "url": "/patrols$overhaulWay",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112333",
          "functionName": "机器人管理",
          "url": "/patrols$robotManage",
          "isFinalnode": 1,
          "icon": null,
        },
      ],
    },
    {
      "id": "27771057835132869",
      "functionName": "在线巡查",
      "url": "inspection",
      "isFinalnode": 0,
      "icon": "",
      "children": [
        {
          "id": "988825242112341",
          "functionName": "巡查任务",
          "url": "/inspection$taskManage",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112343",
          "functionName": "巡查线路",
          "url": "/inspection$overhaulWay",
          "isFinalnode": 1,
          "icon": null,
        },
      ],
    },
    {
      "id": "27771057835132869",
      "functionName": "智能布防",
      "url": "defenses",
      "isFinalnode": 0,
      "icon": "",
      "children": [
        {
          "id": "988825242112341",
          "functionName": "人员布防",
          "url": "/defenses$personDefense",
          "isFinalnode": 1,
          "icon": null,
        },
        {
          "id": "988825242112343",
          "functionName": "车辆布防",
          "url": "/defenses$carDefense",
          "isFinalnode": 1,
          "icon": null,
        },
      ],
    },
  ]
export default datajson